### ISSUE TITLE
Licence of xah-math-input

### ISSUE THREAD

**Issue by brandelune** [xahlee/xah-math-input#1]
Hi,

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html

So I wonder if you could consider to change the license of your package to GPL-3+?

Yours,

Jean-Christophe Helary

**Comment by jwinder** [comment]
Is this the reason the package has disappeared from melpa? https://melpa.org/#/xah-math-input

**Comment by brandelune** [comment]
I don't think so.

**Comment by xahlee** [comment]
i was thinking of withdraw, but was busy and haven't decided. Apparently melpa went along with it and removed none gpl3 packages. I think it's sad.

**Comment by xahlee** [comment]
@brandelune thank you for letting me know though. I know you are helping rms. I can't agree with him after all these years. (i was rms fanatic back from 1999 to about 2006, and pro FSF/GNU/GPL and anti Open Source, if you knew there was a faction and still)

on the other hand, apparently melpa went alone to enforced this gpl3 idea. I got notification from their issue alert. I guess i can still change the license and be part of the boat... but am tired. Maybe later.

**Comment by brandelune** [comment]
If you want, I can create pull requests for all the packages I created an issue for. That way you'll just have to merge and that will be done. Let me know what it the best for you, and thank you for your work, I'm a subscribers to your emacs/elisp tutorial !

**Comment by xahlee** [comment]
@brandelune  You touched me.

If you would change the line

;; You can redistribute this program and/or modify it under the terms of the GNU General Public License version 2.

to

;; You can redistribute this program and/or modify it under the terms of the GNU General Public License version 3.

I'll merge. Thanks a lot.

**Comment by xahlee** [comment]
@brandelune i'm going to start to do it myself. Thank you very much again. (if you still consider helping, please check first if already changed. I should have them all covered today)

**Comment by xahlee** [comment]
@brandelune , i think i updated all my packages to GPL3. Am going to close issues. Thank you again.
