### ISSUE TITLE
package not available on melpa

### ISSUE THREAD

**Issue by philiparvidsson** [xahlee/xah-math-input#3]
I really want to use this, but I can't install it from melpa. is this still a licensing issue or does it just need to be resubmitted? is there anything I can do to help out?

**Comment by xahlee** [comment]
make sure you are not using the stable melpa.

e.g. do this
;; load emacs 24's package system. Add MELPA repository.
(when (>= emacs-major-version 24)
  (require 'package)
  (add-to-list
   'package-archives
   ;; '("melpa" . "http://stable.melpa.org/packages/") ; many packages
won't show if using stable
   '("melpa" . "http://melpa.milkbox.net/packages/")
   t))

i don't know what's the deal with melpa stable.

**Comment by philiparvidsson** [comment]
thanks!
